Repopulate records table with empty QUERY_ROOT after caches are cleared
awslabs/aws-mobile-appsync-sdk-ios pull request #535
Opened 2022-05-16 04:57 UTC by jellybeansoup

*Issue #, if available:*
#92 (kinda?)

*Description of changes:*
As part of working around an issue allowing optimistic updates of query results that haven't been retrieved from the service, @palpatim introduced code to pre-populate an empty table with an empty QUERY_ROOT, resolving the issue. However the issue resurfaces if at any point the caches are cleared, as the table is not then repopulated with the empty QUERY_ROOT.

So if, for example, a user installs an app for the first time and log into an account backed by AWS App Sync, the existing workaround correctly ensures that optimistic updates don't fail when the underlying query results have not been fetched from the service, but if that user were to sign out (causing the caches to be cleared) and then into another account, the workaround is no longer in place, and optimistic updates will fail.

This PR introduces changes to repopulate the cache with the empty QUERY_ROOT immediately after clearing it, thereby ensuring that optimistic updates do not fail after calling `clearCaches()`. The requisite tests have also been updated to showcase the issue, and show that it is resolved.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-05-17 19:54 UTC, atierian commented
Thanks for opening this PR @jellybeansoup. We'll review and get back to you on this shortly.

2022-05-27 18:06 UTC, lawmicha requested changes
Thanks @jellybeansoup for opening this PR, I ran the integration tests and they are passing. Suggestion to refactor some of the code here: https://github.com/awslabs/aws-mobile-appsync-sdk-ios/commit/1552e351c2ed38d545d3bab928a910f07027b36b please cherry-pick or apply a similar change before we merge this in

2022-05-28 01:28 UTC, jellybeansoup commented
Thanks so much, @lawmicha. I've cherry-picked the requested changes; really should've picked up on that myself 😅

2022-05-29 04:25 UTC, lawmicha approved these changes

2022-05-29 04:26 UTC, merged